[package]
name = "argparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
termsize = "0.1.6"
textwrap = "0.16.1"
unicode-width = "0.1.11"

